[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor -Ldefmt"
rustflags = [
    "--cfg",  "espidf_time64",
    # --- Support defmt ---
    "-C", "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
DEFMT_LOG="info"
ESP_IDF_VERSION = "v5.3.2"
ESP_IDF_PATH_ISSUES = "warn"
RUST_BACKTRACE="1"
WIFI_SSID = "YOUR_SSID_HERE"
WIFI_PASSWORD = "YOUR_PASSWORD_HERE"
