[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor -Ldefmt --partition-table ./partitions_singleapp_large.csv"
rustflags = [
    "--cfg",  "espidf_time64",
    # --- Support defmt ---
    "-C", "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
DEFMT_LOG="info"
ESP_IDF_VERSION = "v5.3.2"
ESP_IDF_PATH_ISSUES = "warn"
RUST_BACKTRACE="1"
WIFI_SSID = "YOUR_SSID_HERE"
WIFI_PASSWORD = "YOUR_PASSWORD_HERE"
KASA_DEVICE_ADDR = "1.1.1.1:9999"

MQTT_PROTOCOL = "mqtt" # needs to be mqqts for secure connection
MQTT_SERVER = "io.adafruit.com"
MQTT_PORT = "1883"
MQTT_USERNAME = "MQTT_USERNAME" # for adafruit.io this is your adafruit.io username
MQTT_PASSWORD = "MQTT_PASSOWRD" # for adafruit.io this starts with aio_
MQTT_CLIENT_ID = "btr-01" # specific client id for this client
MQTT_TOPIC = "MQTT_USERNAME/feeds/TOPIC_NAME" # full path to topic name
